### ISSUE TITLE
Syslog stop working after some days

### ISSUE THREAD

**Issue by m4ccbr** [Juniper/open-nti#124]
Hi 

After running the server for a few days I noticed that I cannot see the annotations anymore.
I just tried some commits and I cannot see it any longer. I have 21 devices and I'm sending all syslog messages to the open nti server.

BR
Al

**Comment by 3fr61n** [comment]
Hi m4ccbr, 

Could you please check through influxdb web UI, 

1.-  if there are recent syslog messages in your db
2.- the timestamp between container/server and the routers.  (I'm asking this because influxdb only accepts insert values with timestamp 'from the past or present' time but it won't accept future values)

Regards

**Comment by m4ccbr** [comment]
Hi, how do I check in the database the syslog msg?

BR
Al

**Comment by 3fr61n** [comment]
Open the influxdb webUI  (<ipaddress>:8083)  then browse through the db....

**Comment by m4ccbr** [comment]
Hi,

thx a lot for support, I have done that and I can see that we stopped at 2017-02-03T02:20:36.
here are the time which are configured on the server and the router.

egiklmf@junos> show system uptime 
Current time: 2017-02-03 18:40:08 CET
[root@opennti ~]# date
Fri Feb  3 18:39:14 CET 2017

I just saw the following message when I access the container:

Cannot write data: #<InfluxDB::Error: {"error":"max series per database exceeded: events,daemon=fpc7,device=XXXXX,event=FW,priority=events,source_host=X.X.X.X,timestamp=2017-02-03\\ 18:41:40\\ +0100"}

What does it mean?

BR
Al

**Comment by m4ccbr** [comment]
Hi,

thx a lot for support, I have done that and I can see that we stopped at 2017-02-03T02:20:36.
here are the time which are configured on the server and the router.

root@junos> show system uptime
Current time: 2017-02-03 18:40:08 CET
[root@opennti ~]# date
Fri Feb 3 18:39:14 CET 2017

I just saw the following message when I access the container:

Cannot write data: #<InfluxDB::Error: {"error":"max series per database exceeded: events,daemon=fpc7,device=XXXXX,event=FW,priority=events,source_host=X.X.X.X,timestamp=2017-02-03\ 18:41:40\ +0100"}

What does it mean?

BR
Al

**Comment by 3fr61n** [comment]
Hi

Regarding this message I found this 

https://github.com/influxdata/docs.influxdata.com/issues/710

Not sure how many routers and commands are you executing, but it seems you reach the default limit.  

Could you please open the influxdb web ui (is the main container IP address at port 8083), then select 'show stats' query and check how many meassurements you have (see picture below)

![screen shot 2017-02-06 at 13 17 35](https://cloud.githubusercontent.com/assets/6707509/22646852/ba142ca8-ec6e-11e6-837b-bce055c8a887.png)

As initial workaround follow the link above recommendation, although IMHO the best thing to do is change the data scheme for netconf collector (option 3 in the opennti config variables, however changing this parameter will force you to redefine queries for dashboard, in the upcoming commits will try to put this as default in order to increase overall scalability)

Let me know if this help you
