### ISSUE TITLE
installation warning: warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

### ISSUE THREAD

**Issue by lorenzomurillo** [Juniper/open-nti#17]
Hi team,
when issuing "sudo ./docker.build.sh", a warning appears.
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

Installing on Ubuntu 14.04 Desktop vm
ubuntu@ubuntu-virtual-machine:/usr/share/gnome-connection-manager$ uname -a
Linux ubuntu-virtual-machine 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ubuntu-virtual-machine:/usr/share/gnome-connection-manager$ docker -v
Docker version 1.10.2, build c3959b1

Searching for pycrypto>=2.4.1
Reading https://pypi.python.org/simple/pycrypto/
Best match: pycrypto 2.6.1
Downloading https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf5161a0d5d7eda
Processing pycrypto-2.6.1.tar.gz
Writing /tmp/easy_install-AYsA9B/pycrypto-2.6.1/setup.cfg
Running pycrypto-2.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-AYsA9B/pycrypto-2.6.1/egg-dist-tmp-sOhpcq
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
zip_safe flag not set; analyzing archive contents...
Adding pycrypto 2.6.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pycrypto-2.6.1-py2.7-linux-x86_64.egg

Regards,
Lorenzo

**Comment by 3fr61n** [comment]
Sorry but I'm not being able to reproduce the problem yet


juniper@atum:~/scripts/open-nti$ ./docker.build.sh 
Sending build context to Docker daemon 12.87 MB
Sending build context to Docker daemon 
Step 0 : FROM phusion/baseimage:0.9.18
0.9.18: Pulling from phusion/baseimage

428b411c28f0: Already exists 
....
....
Removing intermediate container 484d7e2d6cd1
Step 54 : CMD /sbin/my_init
 ---> Running in 69fd96146d81
 ---> bbd7e181fb05
Removing intermediate container 69fd96146d81
Successfully built bbd7e181fb05
juniper@atum:~/scripts/open-nti$ docker -v
Docker version 1.7.0, build 0baf609
juniper@atum:~/scripts/open-nti$ uname -a
Linux atum 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
juniper@atum:~/scripts/open-nti$ cat Dockerfile | grep crypto
juniper@atum:~/scripts/open-nti$ 


How do you install docker?  I used, (https://docs.docker.com/engine/installation/linux/ubuntulinux/)  at the end there is an optional commands in order to avoid using 'sudo' each time (this is not related to the problem you found)

**Comment by 3fr61n** [comment]
Ok I got the messages... don't worry about this warning, the only thing that matters is that the docker installation finishes OK

warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
zip_safe flag not set; analyzing archive contents...

Thanks
