### ISSUE TITLE
JET integration enhancement question

### ISSUE THREAD

**Issue by jcbarth** [Juniper/open-nti#87]
Has anyone considered adding support for integrating telemetry data learned from JET?  e.g. RIB API subscription information instead of periodic CLI execution of 'show route ...'?

thanks,

-Colby

**Comment by dgarros** [comment]
HI @jcbarth 
That would be great
I did a quick try the other day to ingest events information from MQTT into OpenNTI using Telegraf
it turns out the MQTT client available for Telegraf today was not compatible with the format sent by Junos on MQTT
with a little development it should be possible
Damien
